<?php

namespace ContainerHw4EyC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DV8Oa9oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DV8Oa9o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DV8Oa9o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', 'App\\Service\\Cart', 'getCartService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'stripeSK' => ['privates', '.value.2mty10Y', 'get_Value_2mty10YService', true],
        ], [
            'cart' => 'App\\Service\\Cart',
            'doctrine' => '?',
            'stripeSK' => '?',
        ]);
    }
}
