<?php

namespace ContainerHw4EyC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YLQVdLFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yLQVdLF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yLQVdLF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coordinate' => ['privates', 'App\\Repository\\CoordinateRepository', 'getCoordinateRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\LigneDeCommandeRepository', 'getLigneDeCommandeRepositoryService', true],
        ], [
            'coordinate' => 'App\\Repository\\CoordinateRepository',
            'repository' => 'App\\Repository\\LigneDeCommandeRepository',
        ]);
    }
}
