<?php

namespace ContainerHw4EyC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_2mty10YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.2mty10Y' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.2mty10Y'] = \current([0 => $container->getEnv('STRIPE_KEY')]);
    }
}
