<?php

namespace ContainerJJ0PIxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_No94FXjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.no94FXj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.no94FXj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.no94FXj.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.no94FXj": it references class "App\\Entity\\Commande" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Commande',
        ]);
    }
}
