<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHw4EyC8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHw4EyC8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHw4EyC8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHw4EyC8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHw4EyC8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hw4EyC8',
    'container.build_id' => 'fdac01a5',
    'container.build_time' => 1706196525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHw4EyC8');
